# Generated by Django 5.1.7 on 2025-03-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_departments_created_at_departments_updated_at_and_more'),
        ('users', '0006_user_created_at_user_updated_at_usercoursepurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departments_taught',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='departments.departments', verbose_name='Departments Taught'),
        ),
    ]
