# Generated by Django 5.1.7 on 2025-03-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_usercoursepurchase'),
        ('users', '0007_user_departments_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', through='departments.UserCoursePurchase', to='departments.course', verbose_name='Purchased Courses'),
        ),
        migrations.DeleteModel(
            name='UserCoursePurchase',
        ),
    ]
