# Generated by Django 5.1.7 on 2025-04-19 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='courseslesson',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.course'),
        ),
        migrations.AddField(
            model_name='coursesofdepartment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.course'),
        ),
        migrations.AddField(
            model_name='departments',
            name='courses',
            field=models.ManyToManyField(through='departments.CoursesOfDepartment', to='departments.course'),
        ),
        migrations.AddField(
            model_name='coursesofdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departments'),
        ),
        migrations.AddField(
            model_name='course',
            name='departmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='departments.departments', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='usercoursepurchase',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.course'),
        ),
        migrations.AddField(
            model_name='usercoursepurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercoursepurchase',
            unique_together={('user', 'course')},
        ),
    ]
