# Generated by Django 5.1.7 on 2025-03-09 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='departmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='departments.departments', verbose_name='Department'),
        ),
    ]
