# Generated by Django 5.1.7 on 2025-03-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_departments_created_at_departments_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursesOfDepratment',
            new_name='CoursesOfDepartment',
        ),
    ]
