# Generated by Django 5.1.7 on 2025-03-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_courseslesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseslesson',
            options={'ordering': ['created_at'], 'verbose_name': 'Course Lesson', 'verbose_name_plural': 'Course Lessons'},
        ),
        migrations.RenameField(
            model_name='courseslesson',
            old_name='course',
            new_name='courseId',
        ),
    ]
