# Generated by Django 5.1.7 on 2025-04-02 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_usercoursepurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseslesson',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='courseslesson',
            name='id',
        ),
        migrations.AddField(
            model_name='courseslesson',
            name='lessonId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
