# Generated by Django 5.1.7 on 2025-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('fileId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='files/')),
                ('fileName', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'file Upload',
                'verbose_name_plural': 'files Upload',
            },
        ),
    ]
