# Generated by Django 5.1.7 on 2025-04-19 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadmodel',
            name='created_by',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileuploadmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
